#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

# Libraries
wclean lib libraries/geometricVoF
wclean lib libraries/transportModels/incompressible
wclean lib libraries/turbulenceModels/incompressible

# laserMeltFoam solver
wclean

